4.10 tasks
Dieyd/ahmadov_places pull request #12
Opened 2022-08-06 17:21 UTC by Dieyd

![4 10 Task1](https://user-images.githubusercontent.com/95929043/183259343-a040adde-3d80-472b-9f93-a678767be684.png)
![4 10 task2](https://user-images.githubusercontent.com/95929043/183259348-7e26a66a-7b0a-46a2-9136-447eb22473f0.png)

2022-08-08 15:53 UTC, GeorgeOblomov commented on lib/ui/screen/sight_details.dart
> +                return LinearProgressIndicator();
Это не принципиально, да и в задание об этом не написано, но как по мне `CircularProgressIndicator` здесь бы больше подошел.

2022-08-08 15:54 UTC, GeorgeOblomov commented on lib/ui/screen/sight_details.dart
> +                  child: SizedBox(
`SizedBox` здесь лишний кажется. Вы ведь в нем не указали никаких значений, высоты или ширины, а значит обернули в него без надобности.

2022-08-08 15:58 UTC, GeorgeOblomov requested changes

2022-08-08 15:58 UTC, GeorgeOblomov commented on lib/ui/screen/sight_details.dart
> +                  child: SizedBox(
Ну да, так и есть. К тому же если вам нужны какие то размеры вне `SvgPicture.asset`, вы можете указать их в самом `Container`

2022-08-08 16:47 UTC, Dieyd commented on lib/ui/screen/sight_details.dart
> +                  child: SizedBox(
> `SizedBox` здесь лишний кажется. Вы ведь в нем не указали никаких значений, высоты или ширины, а значит обернули в него без надобности.

верно, не туда передал высоту и ширину. Планировал передать в сайзбокс. Контейнер оставил чтобы цветом обозначать местоположение кнопки будущей.

2022-08-08 16:49 UTC, Dieyd commented on lib/ui/screen/sight_details.dart
> +                return LinearProgressIndicator();
> Это не принципиально, да и в задание об этом не написано, но как по мне `CircularProgressIndicator` здесь бы больше подошел.

пробовал оба варианта, визуально зашла больше широкая полоска, потому что фотка лежит в стеке, и контент ниже блокирует часть circular индикатора. а если делать его маленьким просто некрасиво. Широкая полоска понравилась чисто визуально.

2022-08-09 14:38 UTC, GeorgeOblomov approved these changes

2022-08-09 14:44 UTC, merged